---
title: "Sensory Processes"
subtitle: "📕🔬📓<br/>Welcome to EXP3104"
author: "Instructor: Ryan Mears, PhD"
date: "ber , 2017"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["libs/remark-css/paper_class.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

Chapter 9 
Perceiving Color
Functions of Color Perception
Color signals help us classify and identify objects.
Color facilitates perceptual organization of elements into objects.
Color vision may provide an evolutionary advantage in foraging for food.
Functions of Color Perception (cont'd.)


Functions of Color Perception (cont'd.)


Color and Light
Newton
Thought white light was mixture of many colors
Individual colors of the spectrum are not mixtures of other colors.
The degree to which beams from each part of the spectrum were “bent” by the second prism was different.


Color and Light (cont'd.)



Reflectance and Transmission
Chromatic colors-blue, green, red
Selective reflection
Achromatic colors-gray, black white

Reflectance and Transmission (cont'd.)


Reflectance and Transmission (cont'd.)


Reflectance and Transmission (cont'd.)
Selective transmission
Only some wavelengths pass through objects.
Transmission curves
Plots of the percentage of light are transmitted at each wavelength.

Reflectance and Transmission (cont'd.)



Color Mixing
Additive color mixture:
Mixing lights of different wavelengths
All wavelengths are available for the observer to see.
Superimposing blue and yellow lights leads to white.
Subtractive color mixture:
Mixing paints with different pigments
Additional pigments reflect fewer wavelengths.
Mixing blue and yellow leads to green.
Color Mixing (cont'd.)
Color Mixing (cont'd.)


Perceptual Dimensions of Colors
Spectral colors
Nonspectral colors
Hues
Saturation
Value


Perceptual Dimensions of Colors (cont'd.)




Perceptual Dimensions of Colors (cont'd.)




The Trichromatic Theory of Color Vision
Proposed by Young and Helmholtz (1800s)
Three different receptor mechanisms are responsible for color vision.
Behavioral evidence:
Color-matching experiments
Observers adjusted amounts of three wavelengths in a comparison field to match a test field of one wavelength.


The Trichromatic Theory of Color Vision (cont'd.)
Results showed that:
It is possible to perform the matching task.
Observers with normal color vision need at least three wavelengths to make the matches.
Observers with color deficiencies can match colors by using only two wavelengths.
The Trichromatic Theory of Color Vision (cont'd.)
Evidence for the Trichromatic Theory
Researchers measured absorption spectra of visual pigments in receptors (1960s).
They found pigments that responded maximally to:
Short wavelengths (419nm)
Medium wavelengths (531nm)
Long wavelengths (558nm)
Later researchers found genetic differences for coding proteins for the three pigments (1980s).
Evidence for the Trichromatic Theory (cont’d.)


Cone Responding and Color Perception
Color perception is based on the response of the three different types of cones.
Responses vary depending on the wavelengths available.
Combinations of the responses across all three cone types lead to perception of all colors.
Color matching experiments show that colors that are perceptually similar (metamers) can be caused by different physical wavelengths.
Cone Responding and Color Perception (cont'd.)


Cone Responding and Color Perception (cont'd.)



Are Three Receptor Mechanisms Necessary for Color Vision?
One receptor type cannot lead to color vision
Absorption of a photon causes the same effect, no matter what the wavelength is.
Any two wavelengths can cause the same response by changing the intensity.
Two receptor types (dichromats) solve this problem, but three types (trichromats) allow for perception of more colors.
Principle of univariance

Are Three Receptor Mechanisms Necessary for Color Vision? (cont'd.)



Are Three Receptor Mechanisms Necessary for Color Vision? (cont'd.)



Vision With Two Receptor Types
Monochromat: person who needs only one wavelength to match any color
Dichromat: person who needs only two wavelengths to match any color
Trichromat: person who needs three wavelengths to match any color
The Opponent-Process Theory of Color Vision
Proposed by Hering (1800s)
Color vision is caused by opposing responses generated by blue and yellow, and by green and red.
Behavioral evidence:
Color afterimages and simultaneous color contrast show the opposing pairings
Types of color blindness are red/green and blue/yellow.
The Opponent-Process Theory of Color Vision (cont'd.)
Opponent-process mechanism proposed by Hering
Three mechanisms: red/green, blue/yellow, and white/black
The pairs respond in an opposing fashion, such as positively to red and negatively to green
These responses were believed to be the result of chemical reactions in the retina.
The Opponent-Process Theory of Color Vision (cont'd.)


The Opponent-Process Theory of Color Vision (cont'd.)
Complementary afterimages
Red and green switch places and blue and yellow switch places.
Hue cancellation method
The Opponent-Process Theory of Color Vision (cont'd.)



Evidence for the Opponent-Process Theory
Researchers performing single-cell recordings found opponent neurons (1950s)
Opponent neurons:
Are located in the retina and LGN
Respond in an excitatory manner to one end of the spectrum and an inhibitory manner to the other
How Opponent Responding Can Be Created by Three Types of Receptors
Each theory describes physiological mechanisms in the visual system
Trichromatic theory explains the responses of the cones in the retina.
Opponent-process theory explains neural response for cells connected to the cones further in the brain.
How Opponent Responding Can Be Created (cont’d.)


How Opponent Responding Can Be Created (cont’d.)


Color in the Cortex
There is no single module for color perception.
Cortical cells in V1, and V4 respond to some wavelengths or have opponent responses.
These cells usually also respond to forms and orientations.
Cortical cells that respond to color may also respond to white.
Color in the Cortex (cont'd.)



Types of Opponent Neurons in the Cortex
Single-opponent neurons
Double-opponent neurons
Types of Opponent Neurons in the Cortex (cont’d.)



Monochromatism
Monochromats have:
A very rare hereditary condition
Only rods and no functioning cones
Ability to perceive only in white, gray, and black tones
True color-blindness
Poor visual acuity
Very sensitive eyes to bright light

Dichromatism
There are three types of dichromatism
Protanopia affects 1% of males and .02% of females.
Individuals see short-wavelengths as blue.
Neutral point occurs at 492nm.
Above neutral point, they see yellow.
They are missing the long-wavelength pigment.
Dichromatism (cont'd.)
Deuteranopia affects 1% of males and .01% of females.
Individuals see short-wavelengths as blue.
Neutral point occurs at 498nm.
Above neutral point, they see yellow.
They are missing the medium wavelength pigment.

Dichromatism (cont'd.)
Tritanopia affects .002% of males and .001% of females.
Individuals see short wavelengths as blue.
Neutral point occurs at 570nm.
Above neutral point, they see red.
They are most probably missing the short wavelength pigment .
Dichromatism (cont'd.)
Dichromatism (cont'd.)


Dichromatism (cont'd.)


Color Constancy
Color constancy: perception of colors as relatively constant in spite of changing light sources
Sunlight has approximately equal amounts of energy at all visible wavelengths.
Tungsten lighting has more energy in the long-wavelengths.
Objects reflect different wavelengths from these two sources.
Color Constancy (cont'd.)
Chromatic adaptation occurs when prolonged exposure to chromatic color leads to receptors:
“Adapting” when the stimulus color selectively bleaches a specific cone pigment
Decreasing in sensitivity to the color
Adaptation occurs to light sources leading to color constancy.

Color Constancy (cont'd.)



Color Constancy (cont'd.)



Color Constancy (cont'd.)
Experiment by Uchikawa et al.
Observers shown sheets of colored paper in three conditions:
Baseline: paper and observer in white light
Observer not adapted: paper illuminated by red light; observer by white
Observer adapted: paper and observer in red light

Color Constancy (cont'd.)
Uchikawa et al. results:
Baseline: green paper is seen as green
Observer not adapted: perception of green paper is shifted toward red
Observer adapted: perception of green paper is slightly shifted toward red
Partial color constancy was shown in this condition.
Color Constancy (cont'd.)


Color Constancy (cont'd.)
Effect of surroundings
Color constancy works best when an object is surrounded by many colors.
Memory and color
Past knowledge of an object’s color can have an impact on color perception.

Color Constancy (cont'd.)
Memory and Color
Experiment by Hansen et al.
Observers saw photographs of fruits with characteristic colors against a gray background.
They adjusted the color of the fruit and a spot of light.
When the spot was adjusted to physically match the background, the spot appeared gray.
But when this was done for the fruits, they were still perceived as being slightly colored.
Lightness Constancy
Achromatic colors are perceived as remaining relatively constant.
Perception of lightness:
Is not related to the amount of light reflected by an object
Is related to the percentage of light reflected by an object
Lightness Constancy (cont'd.)
The ratio principle: two areas that reflect different amounts of light look the same if the ratios of their intensities are the same
This works when objects are evenly illuminated.

Lightness Constancy (cont'd.)



Lightness Perception Under Uneven Illumination
Lightness perception under uneven illumination
Perceptual system must distinguish between:
Reflectance edges: edges where the amount of light reflected changes between two surfaces
Illumination edges: edges where lighting of two surfaces changes
Lightness Perception Under Uneven Illumination (cont'd.)
Sources of information about illumination:
Information in shadows: system must determine that edge of a shadow is an illumination edge
System takes into account the meaningfulness of objects.
Penumbra of shadows signals an illumination edge.
Lightness Perception Under Uneven Illumination (cont'd.)


The Information in Shadows


The Information in Shadows (cont'd.)


Color Is a Creation of the Nervous System
Physical energy in the environment does not have perceptual qualities.
Light waves are not “colored.”
Different nervous systems experience different perceptions.
Honeybees perceive color that is outside human perception.
We cannot tell what color the bee actually “sees.”
Color Is a Creation of the Nervous System (cont'd.)



Infant Color Vision
It is a complex problem to know what an infant really “sees.”
Chromatic color
Brightness
Bornstein et al. (1976)
Habituation
Young infants have color vision.
Infant Color Vision (cont'd.)


 
